# Generated by Django 4.2.27 on 2026-01-28 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=8)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('REVIEWED', 'REVIEWED'), ('FOLLOW_UP', 'FOLLOW_UP'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_messag_convers_6b5f35_idx',
        ),
        migrations.AddField(
            model_name='riskreview',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_reviews', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_event', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['level', 'created_at'], name='chat_riskev_level_e01a42_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_riskev_convers_a2b45d_idx'),
        ),
    ]
