# Generated by Django 4.2.27 on 2026-01-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_riskevent_riskreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
